services:
  - type: web
    name: apple-iphone-17-pro
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production 